// Types
import type { VisaApplication } from "./types";

export const mockVisaApplications: VisaApplication[] = [
  {
    id: "va-001",
    passengerId: "1",
    passengerName: "Ahmed Bin Rashid",
    passportNumber: "N8745123",
    nationality: "Indian",
    dateOfBirth: "1989-03-12",
    destinationCountry: "United Arab Emirates",
    visaType: "Tourist",
    visaCategory: "Single Entry",
    processingType: "Normal",
    embassyConsulate: "UAE Consulate Mumbai",
    intendedTravelDate: "2026-04-10",
    intendedReturnDate: "2026-04-20",
    durationOfStay: 10,
    purposeOfVisit: "Family vacation and sightseeing",
    tripType: "Leisure",
    applicationDate: "2026-03-01",
    expectedDecisionDate: "2026-03-15",
    submissionMode: "VFS",
    vfsCenter: "VFS Global Mumbai",
    referenceNumber: "VFS-UAE-2026-11234",
    documents: [
      { name: "Passport (valid 6 months beyond travel)", required: true, status: "verified" },
      { name: "Passport-size photographs", required: true, status: "verified" },
      { name: "Filled government application form", required: true, status: "verified" },
      { name: "Bank statements (last 3–6 months)", required: true, status: "verified" },
      { name: "Confirmed flight itinerary", required: true, status: "uploaded" },
      { name: "Hotel / accommodation proof", required: true, status: "uploaded" },
      { name: "Travel insurance", required: false, status: "pending" },
      { name: "Cover letter", required: false, status: "pending" },
      { name: "ITR / Salary slips", required: false, status: "uploaded" },
    ],
    visaFeeAmount: 100,
    visaFeeCurrency: "USD",
    serviceFeeAmount: 25,
    totalAmount: 125,
    paymentStatus: "Paid",
    paymentReference: "PAY-2026-0301-A",
    status: "Visa Issued",
    visaNumber: "UAE-TV-2026-88312",
    visaValidFrom: "2026-04-05",
    visaValidTo: "2026-05-05",
    numEntriesGranted: 1,
    statusHistory: [
      { status: "Draft", changedBy: "Admin", changedAt: "2026-03-01T09:00:00Z", note: "Application created" },
      { status: "Documents Pending", changedBy: "Admin", changedAt: "2026-03-01T09:05:00Z", note: "Awaiting passenger documents" },
      { status: "Ready to Submit", changedBy: "Admin", changedAt: "2026-03-05T14:00:00Z", note: "All required documents uploaded" },
      { status: "Submitted", changedBy: "Admin", changedAt: "2026-03-06T10:30:00Z", note: "Submitted at VFS Global Mumbai" },
      { status: "Under Processing", changedBy: "System", changedAt: "2026-03-08T08:00:00Z", note: "Embassy acknowledged receipt" },
      { status: "Approved", changedBy: "System", changedAt: "2026-03-14T16:00:00Z", note: "Visa approved — single entry 30 days" },
      { status: "Visa Issued", changedBy: "Admin", changedAt: "2026-03-15T11:00:00Z", note: "Passport collected with visa sticker" },
    ],
    createdAt: "2026-03-01T09:00:00Z",
    updatedAt: "2026-03-15T11:00:00Z",
  },
  {
    id: "va-002",
    passengerId: "2",
    passengerName: "Fatima Khan",
    passportNumber: "PA239018",
    nationality: "Pakistani",
    dateOfBirth: "1994-08-27",
    destinationCountry: "United Kingdom",
    visaType: "Student",
    visaCategory: "Multiple Entry",
    processingType: "Normal",
    embassyConsulate: "British High Commission Islamabad",
    intendedTravelDate: "2026-09-01",
    intendedReturnDate: "2027-06-30",
    durationOfStay: 302,
    purposeOfVisit: "MSc Data Science at University of Edinburgh",
    tripType: "Education",
    applicationDate: "2026-03-10",
    expectedDecisionDate: "2026-04-25",
    submissionMode: "VFS",
    vfsCenter: "VFS Global Islamabad",
    documents: [
      { name: "Passport (valid 6 months beyond travel)", required: true, status: "verified" },
      { name: "Passport-size photographs", required: true, status: "uploaded" },
      { name: "Filled government application form", required: true, status: "uploaded" },
      { name: "Bank statements (last 3–6 months)", required: true, status: "pending" },
      { name: "Admission / enrollment letter", required: true, status: "uploaded" },
      { name: "Academic transcripts", required: true, status: "uploaded" },
      { name: "Language test scores", required: true, status: "verified" },
      { name: "Travel insurance", required: false, status: "pending" },
      { name: "ITR / Salary slips (sponsor)", required: false, status: "pending" },
    ],
    visaFeeAmount: 490,
    visaFeeCurrency: "GBP",
    serviceFeeAmount: 50,
    totalAmount: 540,
    paymentStatus: "Partial",
    paymentReference: "PAY-2026-0310-B",
    status: "Documents Pending",
    statusHistory: [
      { status: "Draft", changedBy: "Admin", changedAt: "2026-03-10T11:00:00Z", note: "Application created for Tier 4 student visa" },
      { status: "Documents Pending", changedBy: "Admin", changedAt: "2026-03-10T11:15:00Z", note: "Awaiting bank statements and insurance" },
    ],
    createdAt: "2026-03-10T11:00:00Z",
    updatedAt: "2026-03-10T11:15:00Z",
  },
  {
    id: "va-003",
    passengerId: "3",
    passengerName: "Yusuf Ali Hasan",
    passportNumber: "BG771256",
    nationality: "Bangladeshi",
    dateOfBirth: "1983-11-05",
    destinationCountry: "Saudi Arabia",
    visaType: "Tourist",
    visaCategory: "Single Entry",
    processingType: "Express",
    intendedTravelDate: "2026-04-01",
    intendedReturnDate: "2026-04-15",
    durationOfStay: 14,
    purposeOfVisit: "Umrah pilgrimage",
    tripType: "Leisure",
    applicationDate: "2026-03-15",
    expectedDecisionDate: "2026-03-22",
    submissionMode: "Online Portal",
    documents: [
      { name: "Passport (valid 6 months beyond travel)", required: true, status: "verified" },
      { name: "Passport-size photographs", required: true, status: "verified" },
      { name: "Filled government application form", required: true, status: "verified" },
      { name: "Bank statements (last 3–6 months)", required: true, status: "verified" },
      { name: "Confirmed flight itinerary", required: true, status: "verified" },
      { name: "Hotel / accommodation proof", required: true, status: "verified" },
      { name: "Travel insurance", required: false, status: "uploaded" },
    ],
    visaFeeAmount: 80,
    visaFeeCurrency: "SAR",
    serviceFeeAmount: 20,
    totalAmount: 100,
    paymentStatus: "Paid",
    paymentReference: "PAY-2026-0315-C",
    status: "Under Processing",
    statusHistory: [
      { status: "Draft", changedBy: "Admin", changedAt: "2026-03-15T08:00:00Z", note: "Umrah visa application created" },
      { status: "Documents Pending", changedBy: "Admin", changedAt: "2026-03-15T08:10:00Z" },
      { status: "Ready to Submit", changedBy: "Admin", changedAt: "2026-03-16T09:00:00Z", note: "All documents verified" },
      { status: "Submitted", changedBy: "Admin", changedAt: "2026-03-16T10:00:00Z", note: "Submitted via Nusuk portal" },
      { status: "Under Processing", changedBy: "System", changedAt: "2026-03-17T06:00:00Z" },
    ],
    createdAt: "2026-03-15T08:00:00Z",
    updatedAt: "2026-03-17T06:00:00Z",
  },
  {
    id: "va-004",
    passengerId: "4",
    passengerName: "Aisha Noor Rahman",
    passportNumber: "MY991204",
    nationality: "Malaysian",
    dateOfBirth: "1998-01-21",
    destinationCountry: "Japan",
    visaType: "Tourist",
    visaCategory: "Single Entry",
    processingType: "Normal",
    embassyConsulate: "Embassy of Japan Kuala Lumpur",
    intendedTravelDate: "2026-05-10",
    intendedReturnDate: "2026-05-20",
    durationOfStay: 10,
    purposeOfVisit: "Spring sightseeing trip",
    tripType: "Leisure",
    applicationDate: "2026-03-20",
    expectedDecisionDate: "2026-04-10",
    submissionMode: "In-Person",
    documents: [
      { name: "Passport (valid 6 months beyond travel)", required: true, status: "uploaded" },
      { name: "Passport-size photographs", required: true, status: "uploaded" },
      { name: "Filled government application form", required: true, status: "pending" },
      { name: "Bank statements (last 3–6 months)", required: true, status: "pending" },
      { name: "Confirmed flight itinerary", required: true, status: "pending" },
      { name: "Hotel / accommodation proof", required: true, status: "pending" },
    ],
    visaFeeAmount: 30,
    visaFeeCurrency: "USD",
    serviceFeeAmount: 15,
    totalAmount: 45,
    paymentStatus: "Unpaid",
    status: "Draft",
    statusHistory: [
      { status: "Draft", changedBy: "Admin", changedAt: "2026-03-20T14:00:00Z", note: "Application created" },
    ],
    createdAt: "2026-03-20T14:00:00Z",
    updatedAt: "2026-03-20T14:00:00Z",
  },
  {
    id: "va-005",
    passengerId: "5",
    passengerName: "Omar Farooq",
    passportNumber: "SA334109",
    nationality: "Saudi",
    dateOfBirth: "1979-06-03",
    destinationCountry: "Germany",
    visaType: "Business",
    visaCategory: "Multiple Entry",
    processingType: "Express",
    embassyConsulate: "German Embassy Riyadh",
    intendedTravelDate: "2026-04-15",
    intendedReturnDate: "2026-04-22",
    durationOfStay: 7,
    purposeOfVisit: "Trade conference in Frankfurt",
    tripType: "Corporate",
    applicationDate: "2026-03-05",
    expectedDecisionDate: "2026-03-25",
    submissionMode: "VFS",
    vfsCenter: "VFS Global Riyadh",
    referenceNumber: "VFS-DE-2026-54821",
    documents: [
      { name: "Passport (valid 6 months beyond travel)", required: true, status: "verified" },
      { name: "Passport-size photographs", required: true, status: "verified" },
      { name: "Filled government application form", required: true, status: "verified" },
      { name: "Bank statements (last 3–6 months)", required: true, status: "verified" },
      { name: "Confirmed flight itinerary", required: true, status: "verified" },
      { name: "Hotel / accommodation proof", required: true, status: "verified" },
      { name: "Travel insurance", required: false, status: "verified" },
      { name: "Employer NOC / letter", required: true, status: "verified" },
      { name: "Invitation letter (host company)", required: true, status: "verified" },
      { name: "ITR / Salary slips", required: true, status: "verified" },
    ],
    visaFeeAmount: 80,
    visaFeeCurrency: "EUR",
    serviceFeeAmount: 30,
    totalAmount: 110,
    paymentStatus: "Paid",
    paymentReference: "PAY-2026-0305-E",
    status: "Rejected",
    rejectionReason: "Insufficient proof of ties to home country. Additional documentation required.",
    statusHistory: [
      { status: "Draft", changedBy: "Admin", changedAt: "2026-03-05T10:00:00Z", note: "Business visa for Frankfurt trade conference" },
      { status: "Documents Pending", changedBy: "Admin", changedAt: "2026-03-05T10:10:00Z" },
      { status: "Ready to Submit", changedBy: "Admin", changedAt: "2026-03-08T16:00:00Z" },
      { status: "Submitted", changedBy: "Admin", changedAt: "2026-03-09T09:00:00Z", note: "Submitted at VFS Riyadh" },
      { status: "Under Processing", changedBy: "System", changedAt: "2026-03-11T08:00:00Z" },
      { status: "Rejected", changedBy: "System", changedAt: "2026-03-22T14:00:00Z", note: "Insufficient proof of ties to home country" },
    ],
    createdAt: "2026-03-05T10:00:00Z",
    updatedAt: "2026-03-22T14:00:00Z",
  },
  {
    id: "va-006",
    passengerId: "6",
    passengerName: "Maryam Zahra Syed",
    passportNumber: "AE450712",
    nationality: "Emirati",
    dateOfBirth: "1992-12-10",
    destinationCountry: "Turkey",
    visaType: "E-Visa",
    visaCategory: "Multiple Entry",
    processingType: "E-Visa / ETA",
    intendedTravelDate: "2026-04-20",
    intendedReturnDate: "2026-05-04",
    durationOfStay: 14,
    purposeOfVisit: "Istanbul sightseeing and shopping",
    tripType: "Leisure",
    applicationDate: "2026-03-18",
    expectedDecisionDate: "2026-03-20",
    submissionMode: "Online Portal",
    documents: [
      { name: "Passport (valid 6 months beyond travel)", required: true, status: "verified" },
      { name: "Passport-size photographs", required: true, status: "verified" },
      { name: "Filled government application form", required: true, status: "verified" },
      { name: "Bank statements (last 3–6 months)", required: true, status: "verified" },
      { name: "Confirmed flight itinerary", required: true, status: "verified" },
      { name: "Hotel / accommodation proof", required: true, status: "verified" },
    ],
    visaFeeAmount: 50,
    visaFeeCurrency: "USD",
    serviceFeeAmount: 10,
    totalAmount: 60,
    paymentStatus: "Paid",
    paymentReference: "PAY-2026-0318-F",
    status: "Approved",
    visaNumber: "TR-EVISA-2026-44019",
    visaValidFrom: "2026-04-15",
    visaValidTo: "2026-07-14",
    numEntriesGranted: 3,
    statusHistory: [
      { status: "Draft", changedBy: "Admin", changedAt: "2026-03-18T12:00:00Z", note: "E-Visa application initiated" },
      { status: "Documents Pending", changedBy: "Admin", changedAt: "2026-03-18T12:05:00Z" },
      { status: "Ready to Submit", changedBy: "Admin", changedAt: "2026-03-18T13:00:00Z" },
      { status: "Submitted", changedBy: "Admin", changedAt: "2026-03-18T13:30:00Z", note: "Applied via Turkey e-Visa portal" },
      { status: "Under Processing", changedBy: "System", changedAt: "2026-03-18T14:00:00Z" },
      { status: "Approved", changedBy: "System", changedAt: "2026-03-19T09:00:00Z", note: "E-Visa approved — 90 day validity, 3 entries" },
    ],
    createdAt: "2026-03-18T12:00:00Z",
    updatedAt: "2026-03-19T09:00:00Z",
  },
  {
    id: "va-007",
    passengerId: "7",
    passengerName: "Imran Malik",
    passportNumber: "IN553820",
    nationality: "Indian",
    dateOfBirth: "1987-04-14",
    destinationCountry: "Thailand",
    visaType: "Tourist",
    visaCategory: "Single Entry",
    processingType: "On Arrival",
    intendedTravelDate: "2026-04-05",
    intendedReturnDate: "2026-04-12",
    durationOfStay: 7,
    purposeOfVisit: "Family holiday in Bangkok and Pattaya",
    tripType: "Family",
    applicationDate: "2026-03-22",
    submissionMode: "In-Person",
    documents: [
      { name: "Passport (valid 6 months beyond travel)", required: true, status: "verified" },
      { name: "Passport-size photographs", required: true, status: "verified" },
      { name: "Filled government application form", required: true, status: "uploaded" },
      { name: "Bank statements (last 3–6 months)", required: true, status: "uploaded" },
      { name: "Confirmed flight itinerary", required: true, status: "uploaded" },
      { name: "Travel insurance", required: false, status: "pending" },
      { name: "Invitation letter (family member)", required: true, status: "pending" },
      { name: "Relationship / sponsorship proof", required: true, status: "pending" },
    ],
    visaFeeAmount: 2000,
    visaFeeCurrency: "INR",
    serviceFeeAmount: 500,
    totalAmount: 2500,
    paymentStatus: "Unpaid",
    status: "Ready to Submit",
    statusHistory: [
      { status: "Draft", changedBy: "Admin", changedAt: "2026-03-22T09:00:00Z", note: "Family trip visa on arrival" },
      { status: "Documents Pending", changedBy: "Admin", changedAt: "2026-03-22T09:10:00Z" },
      { status: "Ready to Submit", changedBy: "Admin", changedAt: "2026-03-23T06:00:00Z", note: "Core documents ready, on-arrival docs prepared" },
    ],
    createdAt: "2026-03-22T09:00:00Z",
    updatedAt: "2026-03-23T06:00:00Z",
  },
  {
    id: "va-008",
    passengerId: "8",
    passengerName: "Sara Nadeem",
    passportNumber: "PK770154",
    nationality: "Pakistani",
    dateOfBirth: "2000-09-02",
    destinationCountry: "Malaysia",
    visaType: "Medical",
    visaCategory: "Single Entry",
    processingType: "Emergency",
    embassyConsulate: "Malaysian Embassy Islamabad",
    intendedTravelDate: "2026-03-28",
    intendedReturnDate: "2026-04-10",
    durationOfStay: 13,
    purposeOfVisit: "Cardiac surgery consultation at IJN",
    tripType: "Medical",
    applicationDate: "2026-03-21",
    expectedDecisionDate: "2026-03-25",
    submissionMode: "In-Person",
    documents: [
      { name: "Passport (valid 6 months beyond travel)", required: true, status: "verified" },
      { name: "Passport-size photographs", required: true, status: "verified" },
      { name: "Filled government application form", required: true, status: "verified" },
      { name: "Bank statements (last 3–6 months)", required: true, status: "uploaded" },
      { name: "Confirmed flight itinerary", required: true, status: "pending" },
      { name: "Hospital / treatment appointment letter", required: true, status: "verified" },
      { name: "Medical records / referral", required: true, status: "verified" },
      { name: "Travel insurance", required: true, status: "uploaded" },
    ],
    visaFeeAmount: 150,
    visaFeeCurrency: "MYR",
    serviceFeeAmount: 30,
    totalAmount: 180,
    paymentStatus: "Paid",
    paymentReference: "PAY-2026-0321-H",
    status: "Submitted",
    referenceNumber: "MY-EMB-2026-7789",
    statusHistory: [
      { status: "Draft", changedBy: "Admin", changedAt: "2026-03-21T07:00:00Z", note: "Emergency medical visa for cardiac consultation" },
      { status: "Documents Pending", changedBy: "Admin", changedAt: "2026-03-21T07:05:00Z" },
      { status: "Ready to Submit", changedBy: "Admin", changedAt: "2026-03-21T15:00:00Z", note: "Fast-tracked — medical emergency" },
      { status: "Submitted", changedBy: "Admin", changedAt: "2026-03-22T08:00:00Z", note: "Submitted in person at Malaysian Embassy Islamabad" },
    ],
    createdAt: "2026-03-21T07:00:00Z",
    updatedAt: "2026-03-22T08:00:00Z",
  },
];
