/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuppliersIndexRouteImport } from './routes/suppliers/index'
import { Route as CustomersIndexRouteImport } from './routes/customers/index'
import { Route as SuppliersCreateRouteImport } from './routes/suppliers/create'
import { Route as CustomersCreateRouteImport } from './routes/customers/create'
import { Route as AuthRegisterIndexRouteImport } from './routes/auth/register/index'
import { Route as AuthLoginIndexRouteImport } from './routes/auth/login/index'
import { Route as SuppliersSupplierIdEditRouteImport } from './routes/suppliers/$supplierId/edit'
import { Route as CustomersCustomerIdEditRouteImport } from './routes/customers/$customerId/edit'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersIndexRoute = SuppliersIndexRouteImport.update({
  id: '/suppliers/',
  path: '/suppliers/',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersIndexRoute = CustomersIndexRouteImport.update({
  id: '/customers/',
  path: '/customers/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersCreateRoute = SuppliersCreateRouteImport.update({
  id: '/suppliers/create',
  path: '/suppliers/create',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersCreateRoute = CustomersCreateRouteImport.update({
  id: '/customers/create',
  path: '/customers/create',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRegisterIndexRoute = AuthRegisterIndexRouteImport.update({
  id: '/auth/register/',
  path: '/auth/register/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthLoginIndexRoute = AuthLoginIndexRouteImport.update({
  id: '/auth/login/',
  path: '/auth/login/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuppliersSupplierIdEditRoute = SuppliersSupplierIdEditRouteImport.update({
  id: '/suppliers/$supplierId/edit',
  path: '/suppliers/$supplierId/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const CustomersCustomerIdEditRoute = CustomersCustomerIdEditRouteImport.update({
  id: '/customers/$customerId/edit',
  path: '/customers/$customerId/edit',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/customers/create': typeof CustomersCreateRoute
  '/suppliers/create': typeof SuppliersCreateRoute
  '/customers/': typeof CustomersIndexRoute
  '/suppliers/': typeof SuppliersIndexRoute
  '/customers/$customerId/edit': typeof CustomersCustomerIdEditRoute
  '/suppliers/$supplierId/edit': typeof SuppliersSupplierIdEditRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/auth/register/': typeof AuthRegisterIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/customers/create': typeof CustomersCreateRoute
  '/suppliers/create': typeof SuppliersCreateRoute
  '/customers': typeof CustomersIndexRoute
  '/suppliers': typeof SuppliersIndexRoute
  '/customers/$customerId/edit': typeof CustomersCustomerIdEditRoute
  '/suppliers/$supplierId/edit': typeof SuppliersSupplierIdEditRoute
  '/auth/login': typeof AuthLoginIndexRoute
  '/auth/register': typeof AuthRegisterIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/customers/create': typeof CustomersCreateRoute
  '/suppliers/create': typeof SuppliersCreateRoute
  '/customers/': typeof CustomersIndexRoute
  '/suppliers/': typeof SuppliersIndexRoute
  '/customers/$customerId/edit': typeof CustomersCustomerIdEditRoute
  '/suppliers/$supplierId/edit': typeof SuppliersSupplierIdEditRoute
  '/auth/login/': typeof AuthLoginIndexRoute
  '/auth/register/': typeof AuthRegisterIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/customers/create'
    | '/suppliers/create'
    | '/customers/'
    | '/suppliers/'
    | '/customers/$customerId/edit'
    | '/suppliers/$supplierId/edit'
    | '/auth/login/'
    | '/auth/register/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/customers/create'
    | '/suppliers/create'
    | '/customers'
    | '/suppliers'
    | '/customers/$customerId/edit'
    | '/suppliers/$supplierId/edit'
    | '/auth/login'
    | '/auth/register'
  id:
    | '__root__'
    | '/'
    | '/customers/create'
    | '/suppliers/create'
    | '/customers/'
    | '/suppliers/'
    | '/customers/$customerId/edit'
    | '/suppliers/$supplierId/edit'
    | '/auth/login/'
    | '/auth/register/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CustomersCreateRoute: typeof CustomersCreateRoute
  SuppliersCreateRoute: typeof SuppliersCreateRoute
  CustomersIndexRoute: typeof CustomersIndexRoute
  SuppliersIndexRoute: typeof SuppliersIndexRoute
  CustomersCustomerIdEditRoute: typeof CustomersCustomerIdEditRoute
  SuppliersSupplierIdEditRoute: typeof SuppliersSupplierIdEditRoute
  AuthLoginIndexRoute: typeof AuthLoginIndexRoute
  AuthRegisterIndexRoute: typeof AuthRegisterIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers/': {
      id: '/suppliers/'
      path: '/suppliers'
      fullPath: '/suppliers/'
      preLoaderRoute: typeof SuppliersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/': {
      id: '/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof CustomersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers/create': {
      id: '/suppliers/create'
      path: '/suppliers/create'
      fullPath: '/suppliers/create'
      preLoaderRoute: typeof SuppliersCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/create': {
      id: '/customers/create'
      path: '/customers/create'
      fullPath: '/customers/create'
      preLoaderRoute: typeof CustomersCreateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/register/': {
      id: '/auth/register/'
      path: '/auth/register'
      fullPath: '/auth/register/'
      preLoaderRoute: typeof AuthRegisterIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth/login/': {
      id: '/auth/login/'
      path: '/auth/login'
      fullPath: '/auth/login/'
      preLoaderRoute: typeof AuthLoginIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suppliers/$supplierId/edit': {
      id: '/suppliers/$supplierId/edit'
      path: '/suppliers/$supplierId/edit'
      fullPath: '/suppliers/$supplierId/edit'
      preLoaderRoute: typeof SuppliersSupplierIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/customers/$customerId/edit': {
      id: '/customers/$customerId/edit'
      path: '/customers/$customerId/edit'
      fullPath: '/customers/$customerId/edit'
      preLoaderRoute: typeof CustomersCustomerIdEditRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CustomersCreateRoute: CustomersCreateRoute,
  SuppliersCreateRoute: SuppliersCreateRoute,
  CustomersIndexRoute: CustomersIndexRoute,
  SuppliersIndexRoute: SuppliersIndexRoute,
  CustomersCustomerIdEditRoute: CustomersCustomerIdEditRoute,
  SuppliersSupplierIdEditRoute: SuppliersSupplierIdEditRoute,
  AuthLoginIndexRoute: AuthLoginIndexRoute,
  AuthRegisterIndexRoute: AuthRegisterIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
